package SQL;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class Select {

    public static void main(String[] args) throws Exception {
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null; // A table of data representing a database result set, 
        //which is usually generated by executing a statement that queries the database.
        //A ResultSet object maintains a cursor pointing to its current row of data. 
        //Initially the cursor is positioned before the first row. 
        //The next method moves the cursor to the next row,and because it returns false when there are no more rows 
        //in the ResultSet object, it can be used in a while loop to iterate through the result set. 

        String driver = "com.mysql.jdbc.Driver"; // jdbc driver path

        String url = "jdbc:mysql://localhost/student"; // database path
        String username = "root"; // jdbc username
        String password = "admin"; // jdbc password

        Class.forName(driver);//used to load/initlaize the JDBC driver class
        //causes the JDBC driver from some jdbc vendor to be loaded into the application

        conn = DriverManager.getConnection(url, username, password); // establish a connection to database

        System.out.println("conn=" + conn);

        // prepare query
        //String query = "select name,roll from student where rollno LIKE " + 2;
        String query = "select name,roll from student ";

        try {
            // create a statement
            stmt = conn.createStatement(); // create a statement object for sending SQL statements to database

            rs = stmt.executeQuery(query);  // Executes the given SQL statement, which returns a single ResultSet object.

            // extract data from the ResultSet
            while (rs.next()) {
                String id = rs.getString(1);
                String name = rs.getString(2);
                System.out.println("---------------");
                System.out.println("Name: " + id);
                System.out.println("Rollno: " + name);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // release database resources
            try {
                rs.close();
                stmt.close();
                conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

    }
}
